# Generated by Django 3.1.3 on 2021-01-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210101_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='File',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
