# Generated by Django 3.1.3 on 2021-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210101_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
