# Generated by Django 3.1.3 on 2021-01-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210101_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='File',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
