# Generated by Django 3.1.3 on 2021-01-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210101_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='File',
            new_name='Filez',
        ),
    ]
