# Generated by Django 3.1.3 on 2021-01-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210101_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='Filez',
        ),
    ]
