# Generated by Django 3.1.3 on 2021-01-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_files_filez'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='placeholder', upload_to=''),
        ),
    ]
