# Generated by Django 3.1.3 on 2021-01-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210101_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='public',
            field=models.BooleanField(default=False, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
