# Generated by Django 3.1.3 on 2021-01-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='pub_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
