# Generated by Django 3.1.3 on 2021-01-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_files_pub_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='pub_by',
        ),
        migrations.AddField(
            model_name='files',
            name='uploaded_by',
            field=models.CharField(choices=[('admin', 'admin'), ('Greg', 'Greg')], default='1', max_length=50),
        ),
    ]
