# Generated by Django 3.1.3 on 2021-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210103_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='public',
            field=models.BooleanField(null=True),
        ),
    ]
